name: AWS CloudTrail DeleteLoggingConfiguration
id: 24a28726-28f3-4537-a953-71bfbbc3b831
version: 1
date: '2025-02-21'
author: Bhavin Patel, Splunk
description: Data source object for AWS CloudTrail DeleteLoggingConfiguration
source: aws_cloudtrail
sourcetype: aws:cloudtrail
separator: eventName
supported_TA:
- name: Splunk Add-on for AWS
  url: https://splunkbase.splunk.com/app/1876
  version: 7.11.0
fields:
- _time
example_log: ''
