name: O365 Add owner to application.
id: da012cbf-af6e-40ee-a1ba-32a5f8da8f8a
version: 2
date: '2025-01-23'
author: Patrick Bareiss, Splunk
description: Logs the addition of an owner to an application in Microsoft 365, including
  details about the application, the new owner, and the user or administrator performing
  the action.
mitre_components:
- User Account Modification
- Group Modification
- Cloud Service Modification
- Cloud Service Metadata
source: o365
sourcetype: o365:management:activity
separator: Operation
separator_value: Add owner to application.
supported_TA:
- name: Splunk Add-on for Microsoft Office 365
  url: https://splunkbase.splunk.com/app/4055
  version: 4.9.0
fields:
- _time
- ActorContextId
- Actor{}.ID
- Actor{}.Type
- AzureActiveDirectoryEventType
- CreationTime
- ExtendedProperties{}.Name
- ExtendedProperties{}.Value
- Id
- InterSystemsId
- IntraSystemId
- ModifiedProperties{}.Name
- ModifiedProperties{}.NewValue
- ModifiedProperties{}.OldValue
- ObjectId
- Operation
- OrganizationId
- RecordType
- ResultStatus
- SupportTicketId
- TargetContextId
- Target{}.ID
- Target{}.Type
- UserId
- UserKey
- UserType
- Version
- Workload
- action
- additionalDetails
- app
- authentication_service
- change_type
- command
- dataset_name
- date_hour
- date_mday
- date_minute
- date_month
- date_second
- date_wday
- date_year
- date_zone
- dest
- dest_name
- dvc
- event_type
- eventtype
- extendedAuditEventCategory
- host
- index
- linecount
- object
- object_attrs
- object_category
- punct
- record_type
- signature
- source
- sourcetype
- splunk_server
- status
- tag
- tag::eventtype
- timeendpos
- timestartpos
- user
- user_agent
- user_agent_change
- user_id
- user_type
- vendor_account
- vendor_product
example_log: '{"CreationTime": "2023-09-07T13:42:04", "Id": "6e2c723b-8f6e-47f4-8c60-fa23ef3fccee",
  "Operation": "Add owner to application.", "OrganizationId": "48203edf-5d2c-45f2-8123-a368cc8b0e51",
  "RecordType": 8, "ResultStatus": "Success", "UserKey": "1003BFFD98415B4E@contoso.onmicrosoft.com",
  "UserType": 0, "Version": 1, "Workload": "AzureActiveDirectory", "ObjectId": "user2@contoso.onmicrosoft.com",
  "UserId": "user@contoso.onmicrosoft.com", "AzureActiveDirectoryEventType": 1, "ExtendedProperties":
  [{"Name": "additionalDetails", "Value": "{\"User-Agent\":\"Mozilla/5.0 (Macintosh;
  Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0
  Safari/537.36\"}"}, {"Name": "extendedAuditEventCategory", "Value": "Application"}],
  "ModifiedProperties": [{"Name": "Application.ObjectID", "NewValue": "a2d68f8b-ab9f-47ac-934f-b966c3ac134f",
  "OldValue": ""}, {"Name": "Application.DisplayName", "NewValue": "TestApp2", "OldValue":
  ""}, {"Name": "Application.AppId", "NewValue": "95106c0e-3519-450e-8e38-7f326d873454",
  "OldValue": ""}], "Actor": [{"ID": "user@contoso.onmicrosoft.com", "Type": 5}, {"ID":
  "1003BFFD98415B4E", "Type": 3}, {"ID": "18ed3507-a475-4ccb-b669-d66bc9f2a36e", "Type":
  2}, {"ID": "User_e4c722ac-3b83-478d-8f52-c388885dc30f", "Type": 2}, {"ID": "e4c722ac-3b83-478d-8f52-c388885dc30f",
  "Type": 2}, {"ID": "User", "Type": 2}], "ActorContextId": "48203edf-5d2c-45f2-8123-a368cc8b0e51",
  "InterSystemsId": "3f6a58c5-2fba-401d-b137-82b860830213", "IntraSystemId": "e8034ddc-0ca3-4aca-996c-1dc6dee48679",
  "SupportTicketId": "", "Target": [{"ID": "User_57e4bd36-9722-4a4a-9729-7203d8e00b72",
  "Type": 2}, {"ID": "57e4bd36-9722-4a4a-9729-7203d8e00b72", "Type": 2}, {"ID": "User",
  "Type": 2}, {"ID": "user2@contoso.onmicrosoft.com", "Type": 5}, {"ID": "10032002CC029AE9",
  "Type": 3}], "TargetContextId": "48203edf-5d2c-45f2-8123-a368cc8b0e51"}'
output_fields:
- dest
- user
- src
- vendor_account
- vendor_product
