name: Windows Event Log Application 8128
id: 4491537e-5e0c-46f7-9209-f56f852aa237
version: 1
date: '2025-02-26'
author: Michael Haag, Splunk
description: Data source object for Windows Event Log Application 8128
source: XmlWinEventLog:Application
sourcetype: XmlWinEventLog
separator: EventCode
supported_TA:
- name: Splunk Add-on for Microsoft Windows
  url: https://splunkbase.splunk.com/app/742
  version: 9.0.1
fields:
- CategoryString
- Channel
- Computer
- Error_Code
- EventCode
- EventData_Xml
- EventID
- EventRecordID
- EventSourceName
- Guid
- Image_File_Name
- Keywords
- Level
- Name
- Opcode
- ProcessID
- Qualifiers
- RecordNumber
- RenderingInfo_Xml
- SourceName
- SubStatus
- SystemTime
- System_Props_Xml
- Task
- TaskCategory
- ThreadID
- UserID
- Version
- _bkt
- _cd
- _eventtype_color
- _indextime
- _raw
- _serial
- _si
- _sourcetype
- _time
- action
- category
- dest
- dvc
- dvc_nt_host
- event_id
- eventtype
- host
- id
- index
- linecount
- name
- parent_process
- process_name
- punct
- result
- service
- service_id
- service_name
- severity
- severity_id
- signature
- signature_id
- source
- sourcetype
- splunk_server
- splunk_server_group
- status
- subject
- tag
- tag::action
- tag::eventtype
- user_group_id
- user_id
- vendor_product
example_log: <Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='MSSQLSERVER'/><EventID Qualifiers='16384'>8128</EventID><Version>0</Version><Level>4</Level><Task>2</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2025-02-10T20:03:14.2006851Z'/><EventRecordID>16635</EventRecordID><Correlation/><Execution ProcessID='0' ThreadID='0'/><Channel>Application</Channel><Computer>ar-win-2.attackrange.local</Computer><Security/></System><EventData><Data>odsole70.dll</Data><Data>2022.160.1000</Data><Data>sp_OACreate</Data><Binary>C01F00000A00000009000000610072002D00770069006E002D0032000000050000006D007300640062000000</Binary></EventData></Event>

