name: Create Remote Thread In Shell Application
id: 10399c1e-f51e-11eb-b920-acde48001122
version: 8
date: '2025-05-02'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects suspicious process injection in command
  shell applications, specifically targeting `cmd.exe` and `powershell.exe`. It leverages
  Sysmon EventCode 8 to identify the creation of remote threads within these shell
  processes. This activity is significant because it is a common technique used by
  malware, such as IcedID, to inject malicious code and execute it within legitimate
  processes. If confirmed malicious, this behavior could allow an attacker to execute
  arbitrary code, escalate privileges, or maintain persistence within the environment,
  posing a severe threat to system security.
data_source:
- Sysmon EventID 8
search: '`sysmon` EventCode=8 TargetImage IN ("*\\cmd.exe", "*\\powershell*", "*\\pwsh.exe")
  | stats count min(_time) as firstTime max(_time) as lastTime by EventID Guid NewThreadId
  ProcessID SecurityID SourceImage SourceProcessGuid SourceProcessId StartAddress
  StartFunction StartModule TargetImage TargetProcessGuid TargetProcessId UserID dest
  parent_process_exec parent_process_guid parent_process_id parent_process_name parent_process_path
  process_exec process_guid process_id process_name process_path signature signature_id
  user_id vendor_product | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `create_remote_thread_in_shell_application_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA.
known_false_positives: unknown
references:
- https://thedfirreport.com/2021/07/19/icedid-and-cobalt-strike-vs-antivirus/
drilldown_searches:
- name: View the detection results for - "$dest$"
  search: '%original_detection_search% | search  dest = "$dest$"'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
- name: View risk events for the last 7 days for - "$dest$"
  search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$dest$")
    starthoursago=168  | stats count min(_time) as firstTime max(_time) as lastTime
    values(search_name) as "Search Name" values(risk_message) as "Risk Message" values(analyticstories)
    as "Analytic Stories" values(annotations._all) as "Annotations" values(annotations.mitre_attack.mitre_tactic)
    as "ATT&CK Tactics" by normalized_risk_object | `security_content_ctime(firstTime)`
    | `security_content_ctime(lastTime)`'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
rba:
  message: process $process_name$ create a remote thread to shell app process $TargetImage$
    in host $dest$
  risk_objects:
  - field: dest
    type: system
    score: 70
  threat_objects:
  - field: process_name
    type: process_name
tags:
  analytic_story:
  - IcedID
  - Qakbot
  - Warzone RAT
  asset_type: Endpoint
  mitre_attack_id:
  - T1055
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/icedid/simulated_icedid/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: XmlWinEventLog
