name: Potential System Network Configuration Discovery Activity
id: 3f0b95e3-3195-46ac-bea3-84fb59e7fac5
version: 4
date: '2025-05-02'
author: Bhavin Patel, Splunk
status: production
type: Anomaly
description: The following analytic identifies the rapid execution of processes used
  for system network configuration discovery on an endpoint. It leverages data from
  Endpoint Detection and Response (EDR) agents, focusing on process GUIDs, names,
  parent processes, and command-line executions. This activity can be significant
  as it may indicate an attacker attempting to map the network, which is a common
  precursor to lateral movement or further exploitation. If confirmed malicious, this
  behavior could allow an attacker to gain insights into the network topology, identify
  critical systems, and plan subsequent attacks, potentially leading to data exfiltration
  or system compromise.
data_source:
- Sysmon EventID 1
- Windows Event Log Security 4688
- CrowdStrike ProcessRollup2
search: '| tstats `security_content_summariesonly` count values(Processes.process)
  as process values(Processes.parent_process) as parent_process min(_time) as firstTime
  max(_time) as lastTime from datamodel=Endpoint.Processes where NOT Processes.user
  IN ("","unknown") by Processes.action Processes.dest Processes.original_file_name
  Processes.parent_process Processes.parent_process_exec Processes.parent_process_guid
  Processes.parent_process_id Processes.parent_process_name Processes.parent_process_path
  Processes.process Processes.process_exec Processes.process_guid Processes.process_hash
  Processes.process_id Processes.process_integrity_level Processes.process_name Processes.process_path
  Processes.user Processes.user_id Processes.vendor_product _time | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `drop_dm_object_name(Processes)` | search
  `system_network_configuration_discovery_tools` | transaction dest connected=false
  maxpause=5m | where eventcount>=5 | `potential_system_network_configuration_discovery_activity_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: It is uncommon for normal users to execute a series of commands
  used for network discovery. System administrators often use scripts to execute these
  commands. These can generate false positives.
references: []
drilldown_searches:
- name: View the detection results for - "$user$" and "$dest$"
  search: '%original_detection_search% | search  user = "$user$" dest = "$dest$"'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
- name: View risk events for the last 7 days for - "$user$" and "$dest$"
  search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$user$",
    "$dest$") starthoursago=168  | stats count min(_time) as firstTime max(_time)
    as lastTime values(search_name) as "Search Name" values(risk_message) as "Risk
    Message" values(analyticstories) as "Analytic Stories" values(annotations._all)
    as "Annotations" values(annotations.mitre_attack.mitre_tactic) as "ATT&CK Tactics"
    by normalized_risk_object | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
rba:
  message: An instance of $parent_process_name$ spawning multiple $process_name$ was
    identified on endpoint $dest$ by user $user$ typically not a normal behavior of
    the process.
  risk_objects:
  - field: user
    type: user
    score: 32
  - field: dest
    type: system
    score: 32
  threat_objects:
  - field: parent_process_name
    type: parent_process_name
  - field: process_name
    type: process_name
tags:
  analytic_story:
  - Unusual Processes
  asset_type: Endpoint
  mitre_attack_id:
  - T1016
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1016/discovery_commands/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: XmlWinEventLog
