name: Windows Modify Registry DisableSecuritySettings
id: 989019b4-b7aa-418a-9a17-2293e91288b6
version: 8
date: '2025-05-02'
author: Teoderick Contreras, Splunk
status: production
type: TTP
data_source:
  - Sysmon EventID 13
description:
  The following analytic detects modifications to the Windows registry
  that disable security settings for Terminal Services. It leverages the Endpoint
  data model, specifically monitoring changes to the registry path associated with
  Terminal Services security settings. This activity is significant because altering
  these settings can weaken the security posture of Remote Desktop Services, potentially
  allowing unauthorized remote access. If confirmed malicious, such modifications
  could enable attackers to gain persistent remote access to the system, facilitating
  further exploitation and data exfiltration.
search:
  '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Registry where Registry.registry_path = "*\\Terminal
  Services\\DisableSecuritySettings"  Registry.registry_value_data = 0x00000001 by
  Registry.action Registry.dest Registry.process_guid Registry.process_id Registry.registry_hive
  Registry.registry_path Registry.registry_key_name Registry.registry_value_data Registry.registry_value_name
  Registry.registry_value_type Registry.status Registry.user Registry.vendor_product
  | `drop_dm_object_name(Registry)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `windows_modify_registry_disablesecuritysettings_filter`'
how_to_implement:
  To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Registry` node. Also make sure
  that this registry was included in your config files ex. sysmon config to be monitored.
known_false_positives:
  Administrators may enable or disable this feature that may
  cause some false positive, however is not common. Filter as needed.
references:
  - https://malpedia.caad.fkie.fraunhofer.de/details/win.darkgate
drilldown_searches:
  - name: View the detection results for - "$dest$"
    search: '%original_detection_search% | search  dest = "$dest$"'
    earliest_offset: $info_min_time$
    latest_offset: $info_max_time$
  - name: View risk events for the last 7 days for - "$dest$"
    search:
      '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$dest$")
      starthoursago=168  | stats count min(_time) as firstTime max(_time) as lastTime
      values(search_name) as "Search Name" values(risk_message) as "Risk Message" values(analyticstories)
      as "Analytic Stories" values(annotations._all) as "Annotations" values(annotations.mitre_attack.mitre_tactic)
      as "ATT&CK Tactics" by normalized_risk_object | `security_content_ctime(firstTime)`
      | `security_content_ctime(lastTime)`'
    earliest_offset: $info_min_time$
    latest_offset: $info_max_time$
rba:
  message:
    the registry for terminal services settings was modified to disable security
    settings on $dest$.
  risk_objects:
    - field: dest
      type: system
      score: 49
  threat_objects: []
tags:
  analytic_story:
    - DarkGate Malware
    - CISA AA23-347A
  asset_type: Endpoint
  mitre_attack_id:
    - T1112
  product:
    - Splunk Enterprise
    - Splunk Enterprise Security
    - Splunk Cloud
  security_domain: endpoint
tests:
  - name: True Positive Test
    attack_data:
      - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1112/disablesecuritysetting.log
        source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
        sourcetype: XmlWinEventLog
