name: Risk Notable Enrich
id: 010edc96-ff2b-48b0-9f6f-43da3783fd63
version: 1
date: '2021-10-22'
author: Kelby Shelton, Splunk
type: Investigation
description: This playbook collects the available Indicator data types within the event as well as available investigative playbooks. It will launch any playbooks that meet the filtered criteria.
playbook: risk_notable_enrich
how_to_implement: For detailed implementation see https://help.splunk.com/en/splunk-enterprise-security-8/security-content-update/how-to-use-splunk-security-content/5.8/use-splunk-soar-playbooks-and-workbooks-from-the-risk-notable-playbook-pack/get-started-with-the-risk-notable-playbook-pack-for-splunk-soar
references:
  - https://help.splunk.com/en/splunk-enterprise-security-8/security-content-update/how-to-use-splunk-security-content/5.8/use-splunk-soar-playbooks-and-workbooks-from-the-risk-notable-playbook-pack/build-playbooks-compatible-with-the-dispatch_input_playbooks-utility
app_list: []
tags:
  labels:
    - risk_notable
  playbook_outputs:
    - note_title
    - note_content
  playbook_type: Automation
  vpe_type: Modern
  platform_tags:
    - Risk Notable
  product:
    - Splunk SOAR
