name: ESXi Encryption Settings Modified
id: dbbbe26f-83fe-4ee3-8b77-ccf7fbd416c8
version: 1
date: '2025-07-07'
author: Raven Tait, Splunk
status: production
type: TTP
description: Detects the disabling of critical encryption enforcement settings on an ESXi host, such as 
  secure boot or executable verification requirements, which may indicate an attempt to weaken 
  hypervisor integrity or allow unauthorized code execution.
data_source:
- VMWare ESXi Syslog
search: '`esxi_syslog` Message="*system settings encryption set*" NOT Message="*shell.*"
  Message IN ("* -s *", "* -e *","*--require-secure-boot*", "*require-exec-installed-only*", "execInstalledOnly")
  | rex field=_raw "Z (?<dest>[\w\.]*)\s.*\]: \[(?<user>\w+)\]:(?<command>.+)"
  | stats min(_time) as firstTime max(_time) as lastTime count by dest user command
  | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `esxi_encryption_settings_modified_filter`'
how_to_implement: This is based on syslog data generated by VMware ESXi hosts. To implement this search, 
  you must configure your ESXi systems to forward syslog output to your Splunk deployment. These logs must 
  be ingested with the appropriate Splunk Technology Add-on for VMware ESXi Logs, which provides field
  extractions and CIM compatibility. 
known_false_positives: Limited false positives in most environments, however tune
  as needed.
drilldown_searches:
- name: View the detection results for - "$dest$"
  search: '%original_detection_search% | search  dest = "$dest$"'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
- name: View risk events for the last 7 days for - "$dest$"
  search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$dest$")
    starthoursago=168  | stats count min(_time) as firstTime max(_time) as lastTime
    values(search_name) as "Search Name" values(risk_message) as "Risk Message" values(analyticstories)
    as "Analytic Stories" values(annotations._all) as "Annotations" values(annotations.mitre_attack.mitre_tactic)
    as "ATT&CK Tactics" by normalized_risk_object | `security_content_ctime(firstTime)`
    | `security_content_ctime(lastTime)`'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
rba:
  message: Encryption settings modified on ESXi host $dest$.
  risk_objects:
  - field: dest
    type: system
    score: 50
  threat_objects: []
tags:
  analytic_story:
  - ESXi Post Compromise
  - Black Basta Ransomware
  asset_type: Infrastructure
  mitre_attack_id:
  - T1562
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562/esxi_encryption_modified/esxi_encryption_modified.log
    source: vmware:esxlog
    sourcetype: vmw-syslog
