name: Windows Service Stop Via Net  and SC Application
id: 827af04b-0d08-479b-9b84-b7d4644e4b80
version: 5
date: '2025-01-24'
author: Teoderick Contreras, Splunk
status: removed
type: Anomaly
description: The following analytic has been deprecated.
  The following analytic identifies attempts to stop services on a system
  using `net.exe` or `sc.exe`. It leverages data from Endpoint Detection and Response
  (EDR) agents, focusing on process names, GUIDs, and command-line executions. This
  activity is significant as adversaries often terminate security or critical services
  to evade detection and further their objectives. If confirmed malicious, this behavior
  could allow attackers to disable security defenses, facilitate ransomware encryption,
  or disrupt essential services, leading to potential data loss or system compromise.
data_source:
- Sysmon EventID 1
- Windows Event Log Security 4688
- CrowdStrike ProcessRollup2
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime  from datamodel=Endpoint.Processes where `process_net` OR  Processes.process_name
  = "sc.exe" OR Processes.original_file_name= "sc.exe" AND Processes.process="*stop*"
  by  Processes.process_name Processes.original_file_name Processes.process Processes.process_id
  Processes.process_guid Processes.parent_process_name Processes.parent_process Processes.parent_process_guid
  Processes.dest Processes.user | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `windows_service_stop_via_net__and_sc_application_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: Windows OS or software may stop and restart services due to
  some critical update.
references:
- https://www.microsoft.com/en-us/security/blog/2022/10/14/new-prestige-ransomware-impacts-organizations-in-ukraine-and-poland/
drilldown_searches:
- name: View the detection results for - "$dest$"
  search: '%original_detection_search% | search  dest = "$dest$"'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
- name: View risk events for the last 7 days for - "$dest$"
  search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$dest$")
    starthoursago=168  | stats count min(_time) as firstTime max(_time) as lastTime
    values(search_name) as "Search Name" values(risk_message) as "Risk Message" values(analyticstories)
    as "Analytic Stories" values(annotations._all) as "Annotations" values(annotations.mitre_attack.mitre_tactic)
    as "ATT&CK Tactics" by normalized_risk_object | `security_content_ctime(firstTime)`
    | `security_content_ctime(lastTime)`'
  earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
rba:
  message: $process$ was executed on $dest$ attempting to stop service.
  risk_objects:
  - field: dest
    type: system
    score: 49
  threat_objects: []
tags:
  analytic_story:
  - Prestige Ransomware
  - Graceful Wipe Out Attack
  asset_type: Endpoint
  mitre_attack_id:
  - T1489
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/prestige_ransomware/sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: XmlWinEventLog
